### ISSUE TITLE
Weighting Data

### ISSUE THREAD

**Issue by Hadsga** [uyanik/ShapKa#1]
Is there a possibility to use a weight in your module like in a other learners (e.g. linear regression). 

```
import numpy as np
import pandas as pd  
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
import shap


boston = load_boston()
regr = pd.DataFrame(boston.data)
regr.columns = boston.feature_names
regr['MEDV'] = boston.target

X = regr.drop('MEDV', axis = 1)
Y = regr['MEDV']
w = weight # fictive sample weight

fit = LinearRegression().fit(X, Y[, weight])
```

**Comment by uyanik** [comment]
Currently, weighting is not supported. But this is something I'm working on and will add it in the next release.

**Comment by uyanik** [comment]
Weighting is now supported (optional):  

model = KanoModel(df,
                  y_varname, X_varnames,
                  analysis = 'kda',
                  y_dissat_upperbound = 6, y_sat_lowerbound = 9,
                  X_dissat_upperbound = 6, X_sat_lowerbound = 9,
                  weight_varname)
